# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==2.8.2
        pip install astroid==2.5.6
        pip install black==20.8b1
        pip install pytest==6.2.2
        pip install numpy>=1.17.3
        pip install Cython
        pip install wheel
        pip install .
    - name: Run black
      run: |
        black --check .
    - name: Run pylint
      run: |
        pylint --disable=C0330 --fail-under=8 ngs/
        pylint --disable=C0330 --fail-under=8 tests/
    - name: Test with pytest
      run: |
        pytest
